### ISSUE TITLE
Loading locally stored seismograms

### ISSUE THREAD

**Issue by rwalkerlewis** [retrievertech/seismogram-app#20]
I have a local instance of the mongoDB server and web client for SKATE setup using the node-16-mongo-8 branch. I have the pipeline running and have generated output for seismograms I have stored locally. I also see how the convention for seismogram filenames is explained at the top of files.js, and that the list of files and stations are converted into json format from provided text files.

What I do not understand is where the seismograms are supposed to be stored within the file structure and how the pipeline results are included to be imported into the mongoDB so that they can be viewable with the web app. 

Thank you and please advise.

**Comment by bennlich** [comment]
Hiya @rwalkerlewis . Please fetch the latest code from the https://github.com/retrievertech/seismogram-app/commits/node-16-mongo-8/ branch, and also the main branch in https://github.com/retrievertech/seismogram-pipeline/. I just pushed three commits (4301adfd6d58685d8af788b30f70350de40d4590, 2292683ba25cd2bd39286d568d4024abe25d1f86, and https://github.com/retrievertech/seismogram-pipeline/commit/a9409a03b8473c8b4bad5a9142e9d735af716803) to address this issue.

Once you have the latest changes, your local webapp will look for seismogram metadata in the following two local directories instead of s3:
- `client/wwssn-edited-metadata/` (for seismo data that has been processed and also manually edited with the web UI)
- `client/wwssn-metadata/` (for seismo data that has been processed, but not manually edited)

Here is an example of what the directory structure ought to look like for the seismogram 010170_0105_0072_05.png:
```
seismogram-app/
-- client/
---- wwssn-metadata/
------ 010170_0105_0072_05.png/
-------- roi.json
```

Notice that `010170_0105_0072_05.png/` is a directory (although it has a file extension).

After you put the metadata in the right place, you need to update your database so that the client knows that this seismogram has been processed. This can be done with the following command, executed from the `seismogram-pipeline/` directory:

```
bash set_seismo_status.sh 010170_0105_0072_05.png 3 dev
```

You may want to take a look at https://github.com/retrievertech/seismogram-pipeline/blob/master/get_all_metadata_s3.sh#L22-L24. I haven't tested it recently, but this script is designed to do all of the above steps for you, including executing the python processing script.

Hope this helps. Let me know how it goes.

**Comment by rwalkerlewis** [comment]
Thanks. I also had made some fixes in my branch of seismogram-pipeline (local_test) and have rebased that on your new master.

I still do not know where the actual image files are supposed to be stored, and am having great trouble adding anything to the server. After running set_seismo_status.sh with the commands provided in the updated "get_all_metadata_s3.sh" file in my local_test branch, I get the following error on the client side:


```
(seismo) dockimble@overlord:~/Projects/SKATE/seismogram-pipeline$ ./run_local_tests.sh 
Type: dev
writing to /tmp/seismo.xhTeL
set_seismo_status.sh
Type: dev
--2025-02-26 19:32:47--  http://localhost:3000/processing/setstatus/010180_0030_TEST_01.png/1
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Authentication selected: Basic realm=Authorization Required
Reusing existing connection to localhost:3000.
HTTP request sent, awaiting response... 500 Internal Server Error
2025-02-26 19:33:17 ERROR 500: Internal Server Error.

```

and the following error on the client side:
```

(seismo) dockimble@overlord:~/Projects/SKATE/seismogram-app/server$ node server.js 
Seismo app listening in dev mode at http://:::3000
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Topology.selectServer (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/sdam/topology.js:321:38)
    at async Topology._connect (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/sdam/topology.js:200:28)
    at async Topology.connect (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/sdam/topology.js:152:13)
    at async topologyConnect (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/mongo_client.js:233:17)
    at async MongoClient._connect (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/mongo_client.js:246:13)
    at async MongoClient.connect (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/mongo_client.js:171:13)
    at async connect (/home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:20:5)
    at async setStatus (/home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:28:16)
    at async /home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:52:18 {
  errorLabelSet: Set(0) {},
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [cause]: MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
      at Socket.<anonymous> (/home/dockimble/Projects/SKATE/seismogram-app/server/node_modules/mongodb/lib/cmap/connect.js:285:44)
      at Object.onceWrapper (node:events:628:26)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    errorLabelSet: Set(1) { 'ResetPool' },
    beforeHandshake: false,
    [cause]: Error: connect ECONNREFUSED 127.0.0.1:27017
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 27017
    }
  }
}
TypeError: Cannot read properties of undefined (reading 'db')
    at setStatus (/home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:29:29)
    at async /home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:52:18
TypeError: Cannot read properties of undefined (reading 'db')
    at setStatus (/home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:29:29)
    at async /home/dockimble/Projects/SKATE/seismogram-app/server/processing-routes.js:52:18

```

Any help at all would be welcome.

**Comment by rwalkerlewis** [comment]
I may have resolved the database stuff. It is still very new to me. My question about where the actual .png files go still stands.

Thank you.

**Comment by bennlich** [comment]
Hi @rwalkerlewis . That server error you pasted looks like the server was having trouble connecting to your mongo instance. Maybe your mongo server (`mongod`) was not running?

--

Re: where to put your pngs: at the moment, the code (even in development mode) assumes that all pngs are available on s3. When you try to view a seismogram, the server fetches the png from s3, stores it locally, and then chops it into tiles to send to the web client.

You can change this behavior by editing this one line where the server fetches the png from s3: https://github.com/retrievertech/seismogram-app/blob/node-16-mongo-8/server/disk-cache.js#L104

For example, if your images are located at `/path/to/my/local/seismograms/`, you could change the above line to something like:

```
command = `cp /path/to/my/local/seismograms/${filename} ${escape(path)}`;
```

Instead of fetching the image from s3, the server would instead perform a copy command on your local machine.

After making this change, your seismograms will still not have preview thumbnails in the list of seismograms on the homepage, but they should load properly in the viewer when you click on one.

**Comment by rwalkerlewis** [comment]
I have an entire local setup working. Thank you for your help. 

Out of curoisity, where is the client drawing thumbnails? I see that there were a set of thumbnails set on S3 that were used. Is there some way the thumbnail could point toward a default (to avoid rescaling when scrolling through the list)?
